external-services:
  omdb:
    address: "http://www.omdbapi.com/"
    apikey: "fill-me"
    connection:
      connectTimeoutMillis: 100
      socketTimeoutMillis: 500
    retry:
      maxAttempts: 3
      delayMs: 500

cache:
  movieDetails: maximumSize=10000,expireAfterWrite=24h,recordStats
